# Generated by Django 3.2.9 on 2022-12-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=500, null=True)),
                ('Phone', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('Email', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('Gender', models.CharField(blank=True, max_length=500, null=True)),
                ('Password', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='faq',
            name='Idd',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
